export default function Technologies() {
  return (
    <section className="w-full flex flex-col items-center justify-center bg-[var(--clt-dark)] py-15 px-10 gap-10">
      <h1 className="text-[var(--clr-accent)] drop-shadow-md text-5xl">Technologies</h1>
      <div className="flex flex-wrap justify-center items-center gap-6">
        <code>
          <img
            width="80"
            src="https://raw.githubusercontent.com/marwin1991/profile-technology-icons/refs/heads/main/icons/git.png"
            alt="Git"
            title="Git"
          />
        </code>
        <code>
          <img
            width="80"
            src="https://raw.githubusercontent.com/marwin1991/profile-technology-icons/refs/heads/main/icons/github.png"
            alt="GitHub"
            title="GitHub"
          />
        </code>
        <code>
          <img
            width="80"
            src="https://raw.githubusercontent.com/marwin1991/profile-technology-icons/refs/heads/main/icons/visual_studio_code.png"
            alt="Visual Studio Code"
            title="Visual Studio Code"
          />
        </code>
        <code>
          <img
            width="80"
            src="https://raw.githubusercontent.com/marwin1991/profile-technology-icons/refs/heads/main/icons/html.png"
            alt="HTML"
            title="HTML"
          />
        </code>
        <code>
          <img
            width="80"
            src="https://raw.githubusercontent.com/marwin1991/profile-technology-icons/refs/heads/main/icons/css.png"
            alt="CSS"
            title="CSS"
          />
        </code>
        <code>
          <img
            width="80"
            src="https://raw.githubusercontent.com/marwin1991/profile-technology-icons/refs/heads/main/icons/tailwind_css.png"
            alt="Tailwind CSS"
            title="Tailwind CSS"
          />
        </code>
        <code>
          <img
            width="80"
            src="https://raw.githubusercontent.com/marwin1991/profile-technology-icons/refs/heads/main/icons/figma.png"
            alt="Figma"
            title="Figma"
          />
        </code>
        <code>
          <img
            width="80"
            src="https://raw.githubusercontent.com/marwin1991/profile-technology-icons/refs/heads/main/icons/javascript.png"
            alt="JavaScript"
            title="JavaScript"
          />
        </code>
        <code>
          <img
            width="80"
            src="https://raw.githubusercontent.com/marwin1991/profile-technology-icons/refs/heads/main/icons/react.png"
            alt="React"
            title="React"
          />
        </code>
        <code>
          <img
            width="80"
            src="https://raw.githubusercontent.com/marwin1991/profile-technology-icons/refs/heads/main/icons/npm.png"
            alt="npm"
            title="npm"
          />
        </code>
        <code>
          <img
            width="80"
            src="https://raw.githubusercontent.com/marwin1991/profile-technology-icons/refs/heads/main/icons/vite.png"
            alt="Vite"
            title="Vite"
          />
        </code>
        <code>
          <img
            width="80"
            src="https://raw.githubusercontent.com/marwin1991/profile-technology-icons/refs/heads/main/icons/postgresql.png"
            alt="PostgreSQL"
            title="PostgreSQL"
          />
        </code>
      </div>
    </section>
  );
}
