export const technologiesData = [
  {
    id: 1,
    width: 70,
    src: "https://raw.githubusercontent.com/marwin1991/profile-technology-icons/refs/heads/main/icons/git.png",
    alt: "Git",
    title: "Git",
  },
  {
    id: 2,
    width: 70,
    src: "https://raw.githubusercontent.com/marwin1991/profile-technology-icons/refs/heads/main/icons/github.png",
    alt: "GitHub",
    title: "GitHub",
  },
  {
    id: 3,
    width: 70,
    src: "https://raw.githubusercontent.com/marwin1991/profile-technology-icons/refs/heads/main/icons/visual_studio_code.png",
    alt: "Visual Studio Code",
    title: "Visual Studio Code",
  },
  {
    id: 4,
    width: 70,
    src: "https://raw.githubusercontent.com/marwin1991/profile-technology-icons/refs/heads/main/icons/html.png",
    alt: "HTML",
    title: "HTML",
  },
  {
    id: 5,
    width: 70,
    src: "https://raw.githubusercontent.com/marwin1991/profile-technology-icons/refs/heads/main/icons/css.png",
    alt: "CSS",
    title: "CSS",
  },
  {
    id: 6,
    width: 70,
    src: "https://raw.githubusercontent.com/marwin1991/profile-technology-icons/refs/heads/main/icons/tailwind_css.png",
    alt: "Tailwind CSS",
    title: "Tailwind CSS",
  },
  {
    id: 7,
    width: 70,
    src: "https://raw.githubusercontent.com/marwin1991/profile-technology-icons/refs/heads/main/icons/firebase.png",
    alt: "Firebase",
    title: "Firebase",
  },
  {
    id: 8,
    width: 70,
    src: "https://raw.githubusercontent.com/marwin1991/profile-technology-icons/refs/heads/main/icons/figma.png",
    alt: "Figma",
    title: "Figma",
  },
  {
    id: 9,
    width: 70,
    src: "https://raw.githubusercontent.com/marwin1991/profile-technology-icons/refs/heads/main/icons/javascript.png",
    alt: "JavaScript",
    title: "JavaScript",
  },
  {
    id: 10,
    width: 70,
    src: "https://raw.githubusercontent.com/marwin1991/profile-technology-icons/refs/heads/main/icons/react.png",
    alt: "React",
    title: "React",
  },
  {
    id: 11,
    width: 70,
    src: "https://raw.githubusercontent.com/marwin1991/profile-technology-icons/refs/heads/main/icons/typescript.png",
    alt: "TypeScript",
    title: "TypeScript",
  },
  {
    id: 12,
    width: 70,
    src: "https://raw.githubusercontent.com/marwin1991/profile-technology-icons/refs/heads/main/icons/npm.png",
    alt: "npm",
    title: "npm",
  },
  {
    id: 13,
    width: 70,
    src: "https://raw.githubusercontent.com/marwin1991/profile-technology-icons/refs/heads/main/icons/node_js.png",
    alt: "Node.js",
    title: "Node.js",
  },
  {
    id: 14,
    width: 70,
    src: "https://raw.githubusercontent.com/marwin1991/profile-technology-icons/refs/heads/main/icons/express.png",
    alt: "Express",
    title: "Express",
  },
  {
    id: 15,
    width: 70,
    src: "https://raw.githubusercontent.com/marwin1991/profile-technology-icons/refs/heads/main/icons/next_js.png",
    alt: "Next.js",
    title: "Next.js",
  },
  {
    id: 16,
    width: 70,
    src: "https://raw.githubusercontent.com/marwin1991/profile-technology-icons/refs/heads/main/icons/vite.png",
    alt: "Vite",
    title: "Vite",
  },
  {
    id: 17,
    width: 70,
    src: "https://raw.githubusercontent.com/marwin1991/profile-technology-icons/refs/heads/main/icons/postgresql.png",
    alt: "PostgreSQL",
    title: "PostgreSQL",
  },
  {
    id: 18,
    width: 70,
    src: "https://raw.githubusercontent.com/marwin1991/profile-technology-icons/refs/heads/main/icons/sqlite.png",
    alt: "SQLite",
    title: "SQLite",
  },
];
